"""Prescription scans: AI reading (or manual entry) of an uploaded prescription photo.

Triggers:
- the AI result, OCR text and model metadata are frozen once the result is stored;
- only the documented status transitions are allowed;
- verified, rejected and failed scans are final;
- rows are never hard-deleted outside the retention workflow.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 06:10:44.717564+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = ("prescription_scans",)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prescription_scans",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("ai", "manual", name="scan_mode", native_enum=False, create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "needs_review",
                "verified",
                "rejected",
                "failed",
                name="scan_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("ocr_engine", sa.String(length=32), nullable=True),
        sa.Column("image_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "preprocessing",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("provider_response_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=300), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("review", sa.Text(), nullable=True),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verifier_role",
            sa.Enum(
                "patient",
                "caregiver",
                "doctor",
                name="verifier_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "verification_level",
            sa.Enum(
                "unverified",
                "patient_verified",
                "doctor_verified",
                "rejected",
                name="scan_verification_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("rejected_reason", sa.String(length=300), nullable=True),
        sa.Column("prescription_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "image_sha256 IS NULL OR image_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_prescription_scans_image_sha256_hex"),
        ),
        sa.CheckConstraint(
            "mode = 'ai' OR (provider IS NULL AND model IS NULL)",
            name=op.f("ck_prescription_scans_manual_has_no_model"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR error_code IS NOT NULL",
            name=op.f("ck_prescription_scans_failed_has_code"),
        ),
        sa.CheckConstraint(
            "status <> 'rejected' OR rejected_reason IS NOT NULL",
            name=op.f("ck_prescription_scans_rejected_has_reason"),
        ),
        sa.CheckConstraint(
            "status <> 'verified' OR (prescription_id IS NOT NULL AND verified_at IS NOT NULL AND verified_by IS NOT NULL AND verifier_role IS NOT NULL AND verification_level IN ('patient_verified', 'doctor_verified'))",
            name=op.f("ck_prescription_scans_verified_is_complete"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('needs_review', 'verified', 'rejected') OR (result IS NOT NULL AND review IS NOT NULL)",
            name=op.f("ck_prescription_scans_reviewable_has_result"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prescription_scans_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "patient_id"],
            ["health_documents.id", "health_documents.patient_id"],
            name=op.f("fk_prescription_scans_document_id_patient_id_health_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_prescription_scans_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["prescription_id", "patient_id"],
            ["prescriptions.id", "prescriptions.patient_id"],
            name=op.f("fk_prescription_scans_prescription_id_patient_id_prescriptions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_prescription_scans_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_prescription_scans_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["users.id"],
            name=op.f("fk_prescription_scans_verified_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prescription_scans")),
        sa.UniqueConstraint("id", "patient_id", name=op.f("uq_prescription_scans_id_patient_id")),
    )
    op.create_index(
        op.f("ix_prescription_scans_document_id"),
        "prescription_scans",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        "ix_prescription_scans_patient_created",
        "prescription_scans",
        ["patient_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prescription_scans_patient_id"), "prescription_scans", ["patient_id"], unique=False
    )
    op.create_index(
        "uq_prescription_scans_open_per_document",
        "prescription_scans",
        ["document_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running', 'needs_review')"),
    )
    # ### end Alembic commands ###

    op.execute(
        "CREATE TRIGGER trg_prescription_scans_touch_updated_at BEFORE UPDATE ON "
        "prescription_scans FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
    )
    # What the AI produced never changes after it is stored; only the review and outcome do.
    op.execute(
        "CREATE TRIGGER trg_prescription_scans_freeze_result BEFORE UPDATE ON prescription_scans "
        "FOR EACH ROW WHEN (OLD.result IS NOT NULL) EXECUTE FUNCTION hio_freeze_columns("
        "'status', 'review', 'verified_by', 'verified_at', 'verifier_role', "
        "'verification_level', 'rejected_reason', 'prescription_id', "
        "'updated_at', 'updated_by', 'version')"
    )
    op.execute(
        "CREATE TRIGGER trg_prescription_scans_final BEFORE UPDATE ON prescription_scans "
        "FOR EACH ROW WHEN (OLD.status IN ('verified', 'rejected', 'failed')) "
        "EXECUTE FUNCTION hio_freeze_columns('updated_at', 'updated_by', 'version')"
    )
    op.execute(
        "CREATE TRIGGER trg_prescription_scans_transition BEFORE UPDATE ON prescription_scans "
        "FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status) "
        "EXECUTE FUNCTION hio_check_status_transition("
        "'queued>running', 'queued>failed', 'queued>needs_review', 'running>needs_review', "
        "'running>failed', 'needs_review>verified', 'needs_review>rejected')"
    )
    op.execute(
        "CREATE TRIGGER trg_prescription_scans_guard_delete BEFORE DELETE ON prescription_scans "
        "FOR EACH ROW EXECUTE FUNCTION hio_guard_delete()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_prescription_scans_open_per_document",
        table_name="prescription_scans",
        postgresql_where=sa.text("status IN ('queued', 'running', 'needs_review')"),
    )
    op.drop_index(op.f("ix_prescription_scans_patient_id"), table_name="prescription_scans")
    op.drop_index("ix_prescription_scans_patient_created", table_name="prescription_scans")
    op.drop_index(op.f("ix_prescription_scans_document_id"), table_name="prescription_scans")
    op.drop_table("prescription_scans")
    # ### end Alembic commands ###
