"""Medication management: origin labels, pause, history, change requests, duplicates.

- medications.origin (backfilled from the prescription source and scan mode).
- Pause fields; generated name/generic/strength keys for duplicate detection; a unique
  index so the same self-reported medicine cannot be open twice; the view
  medication_possible_duplicates for everything else (same name or same generic).
- medication_events: append-only history; regimen changes need a human actor.
- medication_change_requests: clinically relevant changes waiting for a doctor.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 06:45:46.473112+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = ("medication_events", "medication_change_requests")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medication_change_requests",
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "schedule",
                "stop",
                "pause",
                "other",
                name="change_request_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "declined",
                "withdrawn",
                name="change_request_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column(
            "requester_role",
            sa.Enum(
                "patient",
                "caregiver",
                "doctor",
                "system",
                name="requester_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("proposed", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(status = 'pending') = (resolved_at IS NULL)",
            name=op.f("ck_medication_change_requests_resolved_consistent"),
        ),
        sa.CheckConstraint(
            "kind <> 'schedule' OR proposed IS NOT NULL",
            name=op.f("ck_medication_change_requests_schedule_change_has_proposal"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'declined') OR resolved_by IS NOT NULL",
            name=op.f("ck_medication_change_requests_resolution_has_actor"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_medication_change_requests_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id", "patient_id"],
            ["medications.id", "medications.patient_id"],
            name=op.f("fk_medication_change_requests_medication_id_patient_id_medications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_medication_change_requests_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_medication_change_requests_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("fk_medication_change_requests_resolved_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_medication_change_requests_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_change_requests")),
        sa.UniqueConstraint(
            "id", "patient_id", name=op.f("uq_medication_change_requests_id_patient_id")
        ),
    )
    op.create_index(
        op.f("ix_medication_change_requests_patient_id"),
        "medication_change_requests",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_medication_change_requests_patient_status",
        "medication_change_requests",
        ["patient_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_medication_change_requests_pending",
        "medication_change_requests",
        ["medication_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "medication_events",
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "confirmed",
                "schedule_changed",
                "paused",
                "resumed",
                "stopped",
                "completed",
                "change_requested",
                "change_approved",
                "change_declined",
                "change_withdrawn",
                "duplicate_noted",
                name="medication_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "actor_role",
            sa.Enum(
                "patient",
                "caregiver",
                "doctor",
                "system",
                name="actor_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "advised_by_role",
            sa.Enum(
                "doctor",
                "pharmacist",
                name="advisor_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("advised_by_name", sa.Text(), nullable=True),
        sa.Column("change_request_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "actor_role <> 'system' OR event_type IN ('completed', 'duplicate_noted')",
            name=op.f("ck_medication_events_system_cannot_change_regimen"),
        ),
        sa.CheckConstraint(
            "actor_role = 'system' OR actor_user_id IS NOT NULL",
            name=op.f("ck_medication_events_person_has_user"),
        ),
        sa.CheckConstraint(
            "(advised_by_role IS NULL) = (advised_by_name IS NULL)",
            name=op.f("ck_medication_events_advisor_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_medication_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_medication_events_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id", "patient_id"],
            ["medications.id", "medications.patient_id"],
            name=op.f("fk_medication_events_medication_id_patient_id_medications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_medication_events_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_medication_events_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_medication_events")),
    )
    op.create_index(
        "ix_medication_events_medication_occurred",
        "medication_events",
        ["medication_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_events_patient_id"), "medication_events", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_medication_events_patient_occurred",
        "medication_events",
        ["patient_id", "occurred_at"],
        unique=False,
    )
    op.add_column(
        "medications",
        sa.Column(
            "origin",
            sa.Enum(
                "doctor_prescription",
                "uploaded_prescription_ai",
                "uploaded_prescription_typed",
                "self_reported",
                "clinician_recorded",
                "integration",
                name="medication_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
    )
    op.execute(
        """
        UPDATE medications m SET origin = CASE
            WHEN m.source = 'self_reported' THEN 'self_reported'
            WHEN m.source = 'clinician_recorded' THEN 'clinician_recorded'
            WHEN m.source = 'integration' THEN 'integration'
            WHEN p.source = 'doctor_issued' THEN 'doctor_prescription'
            WHEN EXISTS (SELECT 1 FROM prescription_scans s
                         WHERE s.prescription_id = p.id AND s.mode = 'ai')
                THEN 'uploaded_prescription_ai'
            ELSE 'uploaded_prescription_typed'
        END
        FROM medications m2
        LEFT JOIN prescription_items i ON i.id = m2.prescription_item_id
        LEFT JOIN prescriptions p ON p.id = i.prescription_id
        WHERE m2.id = m.id
        """
    )
    op.alter_column("medications", "origin", nullable=False)
    op.add_column("medications", sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("medications", sa.Column("paused_by", sa.Uuid(), nullable=True))
    op.add_column("medications", sa.Column("pause_reason", sa.String(length=300), nullable=True))
    op.add_column("medications", sa.Column("resume_on", sa.Date(), nullable=True))
    op.add_column(
        "medications",
        sa.Column(
            "name_key",
            sa.String(length=200),
            sa.Computed(
                "lower(regexp_replace(regexp_replace(name, '^\\s*(tab|tabs|tablet|cap|caps|capsule|syp|syrup|susp|suspension|inj|injection|oint|ointment|cream|gel|drop|drops|inh|inhaler|sachet|lotion|spray)\\.?\\s+', '', 'i'), '[^[:alnum:]]+', '', 'g'))",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "medications",
        sa.Column(
            "generic_key",
            sa.String(length=200),
            sa.Computed(
                "CASE WHEN generic_name IS NULL OR btrim(generic_name) = '' THEN NULL ELSE lower(regexp_replace(generic_name, '[^[:alnum:]]+', '', 'g')) END",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "medications",
        sa.Column(
            "strength_key",
            sa.String(length=64),
            sa.Computed(
                "lower(regexp_replace(coalesce(strength, ''), '[^[:alnum:].]+', '', 'g'))",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_medications_patient_name_key_open",
        "medications",
        ["patient_id", "name_key"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending_confirmation', 'active', 'paused')"),
    )
    op.create_index(
        "uq_medications_self_reported_open",
        "medications",
        ["patient_id", "name_key", "strength_key"],
        unique=True,
        postgresql_where=sa.text(
            "source = 'self_reported' AND status IN ('pending_confirmation', 'active', 'paused')"
        ),
    )
    for name, condition in [
        ("paused_consistent", "(status = 'paused') = (paused_at IS NOT NULL)"),
        ("paused_has_actor", "status <> 'paused' OR paused_by IS NOT NULL"),
        ("self_reported_origin", "source <> 'self_reported' OR origin = 'self_reported'"),
        (
            "prescription_origin",
            "origin NOT IN ('doctor_prescription', 'uploaded_prescription_ai', "
            "'uploaded_prescription_typed') OR source = 'prescription'",
        ),
    ]:
        op.create_check_constraint(name, "medications", condition)

    # Possible duplicates among medicines in use: same name (form prefix and punctuation
    # ignored) or same generic. Read by the API; also usable for reporting.
    op.execute(
        """
        CREATE VIEW medication_possible_duplicates AS
        SELECT a.patient_id, a.id AS medication_id, b.id AS duplicate_id,
               CASE WHEN a.name_key = b.name_key THEN 'same_name' ELSE 'same_generic' END
                   AS kind
        FROM medications a
        JOIN medications b ON b.patient_id = a.patient_id AND b.id <> a.id
        WHERE a.status IN ('pending_confirmation', 'active', 'paused')
          AND b.status IN ('pending_confirmation', 'active', 'paused')
          AND (a.name_key = b.name_key
               OR (a.generic_key IS NOT NULL AND a.generic_key IN (b.generic_key, b.name_key))
               OR (b.generic_key IS NOT NULL AND b.generic_key = a.name_key))
        """
    )

    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
        )
    # History is append-only (same function as the audit log).
    op.execute(
        "CREATE TRIGGER trg_medication_events_append_only BEFORE UPDATE OR DELETE ON "
        "medication_events FOR EACH ROW EXECUTE FUNCTION hio_append_only()"
    )
    op.execute(
        "CREATE TRIGGER trg_medication_change_requests_transition BEFORE UPDATE ON "
        "medication_change_requests FOR EACH ROW WHEN (OLD.status IS DISTINCT FROM NEW.status) "
        "EXECUTE FUNCTION hio_check_status_transition("
        "'pending>approved', 'pending>declined', 'pending>withdrawn')"
    )
    op.execute(
        "CREATE TRIGGER trg_medication_change_requests_final BEFORE UPDATE ON "
        "medication_change_requests FOR EACH ROW WHEN (OLD.status <> 'pending') "
        "EXECUTE FUNCTION hio_freeze_columns('updated_at', 'updated_by', 'version')"
    )

    op.create_foreign_key(
        op.f("fk_medications_paused_by_users"),
        "medications",
        "users",
        ["paused_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS medication_possible_duplicates")
    for name in (
        "prescription_origin",
        "self_reported_origin",
        "paused_has_actor",
        "paused_consistent",
    ):
        op.drop_constraint(op.f(f"ck_medications_{name}"), "medications", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_medications_paused_by_users"), "medications", type_="foreignkey")
    op.drop_index(
        "uq_medications_self_reported_open",
        table_name="medications",
        postgresql_where=sa.text(
            "source = 'self_reported' AND status IN ('pending_confirmation', 'active', 'paused')"
        ),
    )
    op.drop_index(
        "ix_medications_patient_name_key_open",
        table_name="medications",
        postgresql_where=sa.text("status IN ('pending_confirmation', 'active', 'paused')"),
    )
    op.drop_column("medications", "strength_key")
    op.drop_column("medications", "generic_key")
    op.drop_column("medications", "name_key")
    op.drop_column("medications", "resume_on")
    op.drop_column("medications", "pause_reason")
    op.drop_column("medications", "paused_by")
    op.drop_column("medications", "paused_at")
    op.drop_column("medications", "origin")
    op.drop_index("ix_medication_events_patient_occurred", table_name="medication_events")
    op.drop_index(op.f("ix_medication_events_patient_id"), table_name="medication_events")
    op.drop_index("ix_medication_events_medication_occurred", table_name="medication_events")
    op.drop_table("medication_events")
    op.drop_index(
        "uq_medication_change_requests_pending",
        table_name="medication_change_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_medication_change_requests_patient_status", table_name="medication_change_requests"
    )
    op.drop_index(
        op.f("ix_medication_change_requests_patient_id"), table_name="medication_change_requests"
    )
    op.drop_table("medication_change_requests")
    # ### end Alembic commands ###
