"""Reminder engine: the NOTIFIED dose state, reminder bookkeeping, push subscriptions.

- medication_doses: status gains 'notified'; notified_at / notify_count; the open-dose
  index includes 'notified'. A trigger freezes everything clinical on a dose row (dose,
  unit, time, medicine, schedule) once written: reminder code can change only the
  state, so it can never change a prescribed dose.
- reminder_preferences.remind_again_after_minutes (one repeat reminder).
- push_subscriptions for Web Push.

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-24 07:08:46.802317+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = ("push_subscriptions",)
STATUSES_OLD = ("scheduled", "snoozed", "taken", "skipped", "missed", "cancelled")
STATUSES_NEW = ("scheduled", "notified", "snoozed", "taken", "skipped", "missed", "cancelled")
# Columns the reminder engine and dose actions may change; everything else is frozen.
DOSE_MUTABLE = (
    'status', 'snoozed_until', 'snooze_count', 'taken_at', 'recorded_by', 'recorded_via',
    'skip_reason', 'notified_at', 'notify_count', 'updated_at', 'updated_by',
)  # fmt: skip


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("endpoint_bidx", sa.String(length=64), nullable=False),
        sa.Column("p256dh", sa.Text(), nullable=False),
        sa.Column("auth", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.String(length=200), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "failure_count >= 0", name=op.f("ck_push_subscriptions_failure_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_subscriptions_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_subscriptions")),
    )
    op.create_index(
        "ix_push_subscriptions_user_live",
        "push_subscriptions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "uq_push_subscriptions_endpoint_live",
        "push_subscriptions",
        ["endpoint_bidx"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.add_column(
        "medication_doses", sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "medication_doses",
        sa.Column("notify_count", sa.SmallInteger(), server_default="0", nullable=False),
    )
    op.add_column(
        "reminder_preferences",
        sa.Column(
            "remind_again_after_minutes", sa.SmallInteger(), server_default="15", nullable=True
        ),
    )
    _dose_status_check(STATUSES_NEW)
    op.create_check_constraint("notify_count_non_negative", "medication_doses", "notify_count >= 0")
    op.create_check_constraint(
        "notified_has_time", "medication_doses", "status <> 'notified' OR notified_at IS NOT NULL"
    )
    op.create_check_constraint(
        "remind_again_range",
        "reminder_preferences",
        "remind_again_after_minutes IS NULL OR remind_again_after_minutes BETWEEN 5 AND 120",
    )
    op.drop_index("ix_medication_doses_open_due", table_name="medication_doses")
    op.create_index(
        "ix_medication_doses_open_due",
        "medication_doses",
        ["scheduled_at"],
        postgresql_where=sa.text("status IN ('scheduled', 'notified', 'snoozed')"),
    )
    args = ", ".join(f"'{c}'" for c in DOSE_MUTABLE)
    op.execute(
        "CREATE TRIGGER trg_medication_doses_clinical_frozen BEFORE UPDATE ON medication_doses "
        f"FOR EACH ROW EXECUTE FUNCTION hio_freeze_columns({args})"
    )
    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
        )


def _dose_status_check(values: tuple[str, ...]) -> None:
    op.drop_constraint(op.f("ck_medication_doses_dose_status"), "medication_doses", type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint("dose_status", "medication_doses", f"status IN ({allowed})")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_medication_doses_clinical_frozen ON medication_doses")
    op.execute(
        "UPDATE medication_doses SET status = 'scheduled', notified_at = NULL "
        "WHERE status = 'notified'"
    )
    op.drop_index("ix_medication_doses_open_due", table_name="medication_doses")
    op.create_index(
        "ix_medication_doses_open_due",
        "medication_doses",
        ["scheduled_at"],
        postgresql_where=sa.text("status IN ('scheduled', 'snoozed')"),
    )
    for table, name in [
        ("reminder_preferences", "remind_again_range"),
        ("medication_doses", "notified_has_time"),
        ("medication_doses", "notify_count_non_negative"),
    ]:
        op.drop_constraint(op.f(f"ck_{table}_{name}"), table, type_="check")
    _dose_status_check(STATUSES_OLD)
    op.drop_column("reminder_preferences", "remind_again_after_minutes")
    op.drop_column("medication_doses", "notify_count")
    op.drop_column("medication_doses", "notified_at")
    op.drop_index(
        "uq_push_subscriptions_endpoint_live",
        table_name="push_subscriptions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index(
        "ix_push_subscriptions_user_live",
        table_name="push_subscriptions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("push_subscriptions")
    # ### end Alembic commands ###
