"""Medical record timeline: symptom reports and database-written record versions.

- symptom_reports: symptoms as the patient, caregiver or doctor described them.
- record_versions: the previous state of a clinical record, copied by an AFTER UPDATE
  trigger (`hio_record_version`) whenever its content changes. Bookkeeping columns
  (updated_at, updated_by, version, plus per-table extras such as a document's virus-scan
  state) do not create versions. The reason comes from the transaction-local setting
  `hio.change_reason` when the service supplies one. Versions are append-only and, like
  other history, can be removed only by the erasure workflow.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-25 07:37:04.937695+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = ("record_versions", "symptom_reports")
# Kept in step with app.modules.timeline.models.VERSIONED_TABLES (checked by a test).
VERSIONED = {
    "medical_conditions": (),
    "allergies": (),
    "medical_history_entries": (),
    "doctor_visits": (),
    "symptom_reports": (),
    "health_documents": ("scan_status", "size_bytes", "sha256"),
    "test_orders": (),
    "test_reports": (),
    "appointments": (),
    "follow_ups": (),
}

FUNCTIONS = (
    r"""
CREATE FUNCTION hio_uuid7() RETURNS uuid
LANGUAGE plpgsql VOLATILE AS $$
DECLARE
    ms bigint := floor(extract(epoch FROM clock_timestamp()) * 1000);
    b bytea := uuid_send(gen_random_uuid());
BEGIN
    b := overlay(b PLACING substring(int8send(ms) FROM 3) FROM 1 FOR 6);
    b := set_byte(b, 6, (get_byte(b, 6) & 15) | 112);
    RETURN encode(b, 'hex')::uuid;
END $$
""",
    r"""
CREATE FUNCTION hio_record_version() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    old_row jsonb := to_jsonb(OLD);
    new_row jsonb := to_jsonb(NEW);
    ignored text[] := ARRAY['updated_at', 'updated_by', 'version'] || coalesce(TG_ARGV, '{}');
    changed text[];
BEGIN
    SELECT coalesce(array_agg(k ORDER BY k), '{}') INTO changed
    FROM jsonb_object_keys(new_row) AS k
    WHERE NOT (k = ANY (ignored)) AND (old_row -> k) IS DISTINCT FROM (new_row -> k);
    IF cardinality(changed) = 0 THEN
        RETURN NULL;
    END IF;
    INSERT INTO record_versions (
        id, patient_id, table_name, record_id, version, snapshot, changed_columns, reason,
        created_by, updated_by
    ) VALUES (
        hio_uuid7(), OLD.patient_id, TG_TABLE_NAME, OLD.id, (old_row ->> 'version')::int,
        old_row, changed, nullif(current_setting('hio.change_reason', true), ''),
        NEW.updated_by, NEW.updated_by
    );
    RETURN NULL;
END $$
""",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_versions",
        sa.Column("table_name", sa.String(length=63), nullable=False),
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("changed_columns", postgresql.ARRAY(sa.String(length=63)), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_record_versions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_record_versions_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_record_versions_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_record_versions")),
    )
    op.create_index(
        op.f("ix_record_versions_patient_id"), "record_versions", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_record_versions_patient_record",
        "record_versions",
        ["patient_id", "table_name", "record_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "symptom_reports",
        sa.Column("symptom", sa.Text(), nullable=False),
        sa.Column("body_site", sa.String(length=100), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "mild",
                "moderate",
                "severe",
                name="symptom_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ongoing",
                "resolved",
                "entered_in_error",
                name="symptom_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("onset_date", sa.Date(), nullable=True),
        sa.Column("resolved_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "doctor",
                "patient",
                "caregiver",
                "ai_extraction",
                "integration",
                "system",
                name="record_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "reported_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("visit_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status <> 'resolved' OR resolved_on IS NOT NULL",
            name=op.f("ck_symptom_reports_resolved_has_date"),
        ),
        sa.CheckConstraint(
            "resolved_on IS NULL OR onset_date IS NULL OR resolved_on >= onset_date",
            name=op.f("ck_symptom_reports_resolved_after_onset"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_symptom_reports_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_symptom_reports_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_symptom_reports_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["visit_id", "patient_id"],
            ["doctor_visits.id", "doctor_visits.patient_id"],
            name=op.f("fk_symptom_reports_visit_id_patient_id_doctor_visits"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symptom_reports")),
        sa.UniqueConstraint("id", "patient_id", name=op.f("uq_symptom_reports_id_patient_id")),
    )
    op.create_index(
        op.f("ix_symptom_reports_patient_id"), "symptom_reports", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_symptom_reports_patient_reported",
        "symptom_reports",
        ["patient_id", "reported_at"],
        unique=False,
    )
    # ### end Alembic commands ###
    for fn in FUNCTIONS:
        op.execute(fn)
    for table, extra in VERSIONED.items():
        args = ", ".join(f"'{c}'" for c in extra)
        op.execute(
            f"CREATE TRIGGER trg_{table}_record_version AFTER UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION hio_record_version({args})"
        )
    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
        )
    op.execute(
        "CREATE TRIGGER trg_record_versions_append_only BEFORE UPDATE ON record_versions "
        "FOR EACH ROW EXECUTE FUNCTION hio_append_only()"
    )
    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_guard_delete BEFORE DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_guard_delete()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in VERSIONED:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_record_version ON {table}")
    # Dropping the tables drops their own triggers.
    op.execute("DROP FUNCTION IF EXISTS hio_record_version()")
    op.execute("DROP FUNCTION IF EXISTS hio_uuid7()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_symptom_reports_patient_reported", table_name="symptom_reports")
    op.drop_index(op.f("ix_symptom_reports_patient_id"), table_name="symptom_reports")
    op.drop_table("symptom_reports")
    op.drop_index("ix_record_versions_patient_record", table_name="record_versions")
    op.drop_index(op.f("ix_record_versions_patient_id"), table_name="record_versions")
    op.drop_table("record_versions")
    # ### end Alembic commands ###
