"""Test and report management: report metadata, review of uploaded reports, per-report
sharing with a doctor.

- test_reports: test_name, report_date, lab_reference, notes (encrypted), and review
  fields (reviewed_at/by, review_note). A rejected or withdrawn report must say why.
- Verified reports stay frozen (migration 0002); the freeze now also lets the review
  fields change, because marking a verified report "entered in error" records who and why.
- report_shares: a patient shares one report with one linked doctor; revocable, optional
  expiry, versioned like other records (migration 0011).

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-25 07:46:29.461072+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = ("report_shares",)
LIFECYCLE = ("updated_at", "updated_by", "version")
REVIEW = ("review_note", "reviewed_at", "reviewed_by")


def _freeze(*cols: str) -> None:
    args = ", ".join(f"'{c}'" for c in ("status", *cols, *LIFECYCLE))
    op.execute("DROP TRIGGER trg_test_reports_freeze ON test_reports")
    op.execute(
        "CREATE TRIGGER trg_test_reports_freeze BEFORE UPDATE ON test_reports "
        "FOR EACH ROW WHEN (OLD.status = 'verified') "
        f"EXECUTE FUNCTION hio_freeze_columns({args})"
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_shares",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("doctor_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "revoked_at IS NULL OR revoked_by IS NOT NULL",
            name=op.f("ck_report_shares_revoked_has_actor"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_report_shares_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor_profiles.id"],
            name=op.f("fk_report_shares_doctor_id_doctor_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_report_shares_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id", "patient_id"],
            ["test_reports.id", "test_reports.patient_id"],
            name=op.f("fk_report_shares_report_id_patient_id_test_reports"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
            name=op.f("fk_report_shares_revoked_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_report_shares_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_shares")),
    )
    op.create_index(
        "ix_report_shares_patient_doctor",
        "report_shares",
        ["patient_id", "doctor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_shares_patient_id"), "report_shares", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_shares_report_id"), "report_shares", ["report_id"], unique=False
    )
    op.create_index(
        "uq_report_shares_live",
        "report_shares",
        ["report_id", "doctor_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.add_column("test_reports", sa.Column("test_name", sa.String(length=200), nullable=True))
    op.add_column("test_reports", sa.Column("report_date", sa.Date(), nullable=True))
    op.add_column("test_reports", sa.Column("lab_reference", sa.String(length=100), nullable=True))
    op.add_column("test_reports", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "test_reports", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("test_reports", sa.Column("reviewed_by", sa.Uuid(), nullable=True))
    op.add_column("test_reports", sa.Column("review_note", sa.String(length=300), nullable=True))
    op.create_foreign_key(
        op.f("fk_test_reports_reviewed_by_users"),
        "test_reports",
        "users",
        ["reviewed_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "closed_has_reason",
        "test_reports",
        "status NOT IN ('rejected', 'entered_in_error') OR review_note IS NOT NULL",
    )
    _freeze(*REVIEW)
    op.execute(
        "CREATE TRIGGER trg_report_shares_touch_updated_at BEFORE UPDATE ON report_shares "
        "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
    )
    op.execute(
        "CREATE TRIGGER trg_report_shares_guard_delete BEFORE DELETE ON report_shares "
        "FOR EACH ROW EXECUTE FUNCTION hio_guard_delete()"
    )
    op.execute(
        "CREATE TRIGGER trg_report_shares_record_version AFTER UPDATE ON report_shares "
        "FOR EACH ROW EXECUTE FUNCTION hio_record_version()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    _freeze()
    op.drop_constraint(op.f("ck_test_reports_closed_has_reason"), "test_reports", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_test_reports_reviewed_by_users"), "test_reports", type_="foreignkey"
    )
    op.drop_column("test_reports", "review_note")
    op.drop_column("test_reports", "reviewed_by")
    op.drop_column("test_reports", "reviewed_at")
    op.drop_column("test_reports", "notes")
    op.drop_column("test_reports", "lab_reference")
    op.drop_column("test_reports", "report_date")
    op.drop_column("test_reports", "test_name")
    op.drop_index(
        "uq_report_shares_live",
        table_name="report_shares",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index(op.f("ix_report_shares_report_id"), table_name="report_shares")
    op.drop_index(op.f("ix_report_shares_patient_id"), table_name="report_shares")
    op.drop_index("ix_report_shares_patient_doctor", table_name="report_shares")
    op.drop_table("report_shares")
    # ### end Alembic commands ###
