"""AI health assistant: conversations, messages, per-user privacy preferences and the
trusted knowledge library (reviewed texts from allow-listed publishers, searched with
PostgreSQL full-text search).

Conversations and messages are the user's own chats, not clinical records: they can be
deleted by their owner and are purged after the owner's retention period.

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-25 08:23:55.450752+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013"
down_revision: str | Sequence[str] | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = (
    "assistant_conversations",
    "assistant_messages",
    "assistant_preferences",
    "knowledge_chunks",
    "knowledge_documents",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("history_days", sa.SmallInteger(), server_default="30", nullable=False),
        sa.Column("save_by_default", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("use_records", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "history_days IN (1, 7, 30, 90)",
            name=op.f("ck_assistant_preferences_history_days_choice"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assistant_preferences_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_assistant_preferences_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_assistant_preferences_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_preferences")),
    )
    op.create_index(
        "uq_assistant_preferences_user", "assistant_preferences", ["user_id"], unique=True
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("publisher", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column(
            "medicines",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=200), nullable=False),
        sa.Column("reviewed_on", sa.Date(), nullable=False),
        sa.Column("review_due", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "retired",
                name="knowledge_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_knowledge_documents_sha256_hex")
        ),
        sa.CheckConstraint(
            "review_due >= reviewed_on", name=op.f("ck_knowledge_documents_review_due_after_review")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_knowledge_documents_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_knowledge_documents_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_documents")),
    )
    op.create_index(
        "uq_knowledge_documents_source_url",
        "knowledge_documents",
        ["publisher", "url"],
        unique=True,
    )
    op.create_table(
        "assistant_conversations",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assistant_conversations_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_assistant_conversations_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_assistant_conversations_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_assistant_conversations_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_conversations")),
        sa.UniqueConstraint(
            "id", "patient_id", name=op.f("uq_assistant_conversations_id_patient_id")
        ),
    )
    op.create_index(
        "ix_assistant_conversations_expires",
        "assistant_conversations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_conversations_patient_id"),
        "assistant_conversations",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_assistant_conversations_patient_owner",
        "assistant_conversations",
        ["patient_id", "owner_user_id"],
        unique=False,
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=300), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(heading, '')), 'A') || setweight(to_tsvector('english', body), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_knowledge_chunks_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
            name=op.f("fk_knowledge_chunks_document_id_knowledge_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_knowledge_chunks_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_chunks")),
    )
    op.create_index(
        "ix_knowledge_chunks_search",
        "knowledge_chunks",
        ["search"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "uq_knowledge_chunks_document_seq", "knowledge_chunks", ["document_id", "seq"], unique=True
    )
    op.create_table(
        "assistant_messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "user", "assistant", name="message_role", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "meta", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id", "patient_id"],
            ["assistant_conversations.id", "assistant_conversations.patient_id"],
            name=op.f("fk_assistant_messages_conversation_id_patient_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assistant_messages_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_assistant_messages_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_assistant_messages_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_messages")),
    )
    op.create_index(
        "ix_assistant_messages_patient_conversation",
        "assistant_messages",
        ["patient_id", "conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_messages_patient_id"), "assistant_messages", ["patient_id"], unique=False
    )
    # ### end Alembic commands ###
    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistant_messages_patient_id"), table_name="assistant_messages")
    op.drop_index("ix_assistant_messages_patient_conversation", table_name="assistant_messages")
    op.drop_table("assistant_messages")
    op.drop_index("uq_knowledge_chunks_document_seq", table_name="knowledge_chunks")
    op.drop_index(
        "ix_knowledge_chunks_search", table_name="knowledge_chunks", postgresql_using="gin"
    )
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_assistant_conversations_patient_owner", table_name="assistant_conversations")
    op.drop_index(
        op.f("ix_assistant_conversations_patient_id"), table_name="assistant_conversations"
    )
    op.drop_index("ix_assistant_conversations_expires", table_name="assistant_conversations")
    op.drop_table("assistant_conversations")
    op.drop_index("uq_knowledge_documents_source_url", table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index("uq_assistant_preferences_user", table_name="assistant_preferences")
    op.drop_table("assistant_preferences")
    # ### end Alembic commands ###
