"""Medication safety: trusted drug reference data and per-patient safety warnings.

- reference_datasets / drug_products / drug_interactions / drug_contraindications /
  allergy_class_members: structured data from allow-listed sources, loaded only by
  scripts/import_drug_reference.py. Nothing is shipped here; no interaction is invented.
- safety_warnings: what the safety engine found for a patient, with source, severity,
  timestamps and review status. Warnings are history: never hard-deleted, and review
  changes are versioned (record_versions trigger).

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-26 18:24:59.859556+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TOUCH_TABLES = (
    "allergy_class_members",
    "drug_contraindications",
    "drug_interactions",
    "drug_products",
    "reference_datasets",
    "safety_warnings",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_datasets",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("publisher", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("license", sa.String(length=200), nullable=False),
        sa.Column("reviewed_by", sa.String(length=200), nullable=False),
        sa.Column("reviewed_on", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "retired",
                name="dataset_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_reference_datasets_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_reference_datasets_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_datasets")),
    )
    op.create_index(
        "uq_reference_datasets_active_key",
        "reference_datasets",
        ["key"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_reference_datasets_key_version", "reference_datasets", ["key", "version"], unique=True
    )
    op.create_table(
        "allergy_class_members",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("class_key", sa.String(length=100), nullable=False),
        sa.Column("class_label", sa.String(length=200), nullable=False),
        sa.Column("ingredient", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_allergy_class_members_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["reference_datasets.id"],
            name=op.f("fk_allergy_class_members_dataset_id_reference_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_allergy_class_members_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allergy_class_members")),
    )
    op.create_index(
        "ix_allergy_class_members_class", "allergy_class_members", ["class_key"], unique=False
    )
    op.create_index(
        op.f("ix_allergy_class_members_dataset_id"),
        "allergy_class_members",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        "ix_allergy_class_members_ingredient", "allergy_class_members", ["ingredient"], unique=False
    )
    op.create_table(
        "drug_contraindications",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient", sa.String(length=200), nullable=False),
        sa.Column("icd10_prefix", sa.String(length=10), nullable=False),
        sa.Column("condition_label", sa.String(length=200), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "minor",
                "moderate",
                "major",
                "contraindicated",
                name="source_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_drug_contraindications_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["reference_datasets.id"],
            name=op.f("fk_drug_contraindications_dataset_id_reference_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_drug_contraindications_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drug_contraindications")),
    )
    op.create_index(
        op.f("ix_drug_contraindications_dataset_id"),
        "drug_contraindications",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        "ix_drug_contraindications_ingredient",
        "drug_contraindications",
        ["ingredient"],
        unique=False,
    )
    op.create_table(
        "drug_interactions",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_a", sa.String(length=200), nullable=False),
        sa.Column("ingredient_b", sa.String(length=200), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "minor",
                "moderate",
                "major",
                "contraindicated",
                name="source_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "ingredient_a < ingredient_b", name=op.f("ck_drug_interactions_ordered_pair")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_drug_interactions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["reference_datasets.id"],
            name=op.f("fk_drug_interactions_dataset_id_reference_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_drug_interactions_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drug_interactions")),
    )
    op.create_index(
        op.f("ix_drug_interactions_dataset_id"), "drug_interactions", ["dataset_id"], unique=False
    )
    op.create_index(
        "ix_drug_interactions_pair",
        "drug_interactions",
        ["ingredient_a", "ingredient_b"],
        unique=False,
    )
    op.create_table(
        "drug_products",
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("name_key", sa.String(length=300), nullable=False),
        sa.Column("ingredients", postgresql.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("dosage_form", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_drug_products_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["reference_datasets.id"],
            name=op.f("fk_drug_products_dataset_id_reference_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_drug_products_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drug_products")),
    )
    op.create_index("ix_drug_products_code", "drug_products", ["code"], unique=False)
    op.create_index(
        op.f("ix_drug_products_dataset_id"), "drug_products", ["dataset_id"], unique=False
    )
    op.create_index("ix_drug_products_name_key", "drug_products", ["name_key"], unique=False)
    op.create_table(
        "safety_warnings",
        sa.Column(
            "kind",
            sa.Enum(
                "duplicate_medication",
                "duplicate_ingredient",
                "interaction",
                "contraindication",
                "allergy",
                "inconsistent_prescription",
                name="warning_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "caution",
                "serious",
                name="warning_severity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_severity", sa.String(length=32), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("patient_detail", sa.Text(), nullable=False),
        sa.Column("clinician_detail", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=True),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.Column("dataset_id", sa.Uuid(), nullable=True),
        sa.Column("subjects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("needs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open", "resolved", name="warning_status", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "unreviewed",
                "acknowledged",
                "reviewed",
                name="review_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewer_role", sa.String(length=20), nullable=True),
        sa.Column("review_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(status = 'resolved') = (resolved_at IS NOT NULL)",
            name=op.f("ck_safety_warnings_resolved_consistent"),
        ),
        sa.CheckConstraint(
            "review_status = 'unreviewed' OR (reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL)",
            name=op.f("ck_safety_warnings_reviewed_has_reviewer"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_safety_warnings_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["reference_datasets.id"],
            name=op.f("fk_safety_warnings_dataset_id_reference_datasets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient_profiles.id"],
            name=op.f("fk_safety_warnings_patient_id_patient_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_safety_warnings_reviewed_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_safety_warnings_updated_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_safety_warnings")),
    )
    op.create_index(
        op.f("ix_safety_warnings_patient_id"), "safety_warnings", ["patient_id"], unique=False
    )
    op.create_index(
        "ix_safety_warnings_patient_status",
        "safety_warnings",
        ["patient_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_safety_warnings_open_fingerprint",
        "safety_warnings",
        ["patient_id", "fingerprint"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###
    for table in TOUCH_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION hio_touch_updated_at()"
        )
    op.execute(
        "CREATE TRIGGER trg_safety_warnings_guard_delete BEFORE DELETE ON safety_warnings "
        "FOR EACH ROW EXECUTE FUNCTION hio_guard_delete()"
    )
    op.execute(
        "CREATE TRIGGER trg_safety_warnings_record_version AFTER UPDATE ON safety_warnings "
        "FOR EACH ROW EXECUTE FUNCTION hio_record_version('last_checked_at')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_safety_warnings_open_fingerprint",
        table_name="safety_warnings",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_safety_warnings_patient_status", table_name="safety_warnings")
    op.drop_index(op.f("ix_safety_warnings_patient_id"), table_name="safety_warnings")
    op.drop_table("safety_warnings")
    op.drop_index("ix_drug_products_name_key", table_name="drug_products")
    op.drop_index(op.f("ix_drug_products_dataset_id"), table_name="drug_products")
    op.drop_index("ix_drug_products_code", table_name="drug_products")
    op.drop_table("drug_products")
    op.drop_index("ix_drug_interactions_pair", table_name="drug_interactions")
    op.drop_index(op.f("ix_drug_interactions_dataset_id"), table_name="drug_interactions")
    op.drop_table("drug_interactions")
    op.drop_index("ix_drug_contraindications_ingredient", table_name="drug_contraindications")
    op.drop_index(op.f("ix_drug_contraindications_dataset_id"), table_name="drug_contraindications")
    op.drop_table("drug_contraindications")
    op.drop_index("ix_allergy_class_members_ingredient", table_name="allergy_class_members")
    op.drop_index(op.f("ix_allergy_class_members_dataset_id"), table_name="allergy_class_members")
    op.drop_index("ix_allergy_class_members_class", table_name="allergy_class_members")
    op.drop_table("allergy_class_members")
    op.drop_index("uq_reference_datasets_key_version", table_name="reference_datasets")
    op.drop_index(
        "uq_reference_datasets_active_key",
        table_name="reference_datasets",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("reference_datasets")
    # ### end Alembic commands ###
